"""Prompt assembly, the refusal sentinel, and decline copy.

Declines are generated by the server, never by the model — that is what makes
them consistent, testable, and identical between the eval harness and the UI
(spec 6.8).
"""
from __future__ import annotations

from dataclasses import dataclass

SENTINEL = "INSUFFICIENT_CONTEXT"

DECLINE_COPY = {
    "empty_corpus": (
        "No documents have been uploaded yet. Upload a medical reference document "
        "and I'll answer questions grounded in it."
    ),
    "off_domain": (
        "I can only answer questions grounded in the medical documents you've "
        "uploaded, and this question doesn't relate to them."
    ),
    "weak_unsupported": (
        "I found some possibly related material, but not close enough to answer "
        "this reliably. Try rephrasing, or upload a document that covers it."
    ),
    "insufficient_context": (
        "Your uploaded documents cover this topic, but don't contain enough detail "
        "to answer this specific question. I'd rather decline than guess."
    ),
}

FALLBACK_DECLINE = (
    "I can't answer that from the documents you've uploaded."
)

SYSTEM_TEMPLATE = """You are a clinical reference assistant for the user's uploaded medical documents.

Answer only using the context below, drawn from documents the user has uploaded.
Do not draw on general knowledge beyond what is in the context.

If the context does not contain enough information to answer the question, reply with
exactly {sentinel} and nothing else. Do not apologise, explain, or add any other text.

When you do answer, cite the numbered sources you used, like [1] or [2].
Your answers are for informational reference only and are not a substitute for
professional medical judgment.

Context:
{context}"""


@dataclass(frozen=True)
class ContextChunk:
    chunk_id: str
    title: str
    page_number: int
    text: str


def decline_text(reason: str) -> str:
    return DECLINE_COPY.get(reason, FALLBACK_DECLINE)


def format_context(chunks: list[ContextChunk]) -> str:
    return "\n\n".join(
        f"[{i}] ({c.title}, p. {c.page_number})\n{c.text}"
        for i, c in enumerate(chunks, start=1)
    )


def _trim_history(history: list[dict], max_history: int, history_chars: int) -> list[dict]:
    recent = history[-max_history:] if max_history else []
    kept: list[dict] = []
    budget = history_chars
    for message in reversed(recent):
        cost = len(message["content"])
        if cost > budget:
            break
        budget -= cost
        kept.append(message)
    return list(reversed(kept))


def build_messages(
    question: str,
    chunks: list[ContextChunk],
    history: list[dict],
    max_history: int = 4,
    history_chars: int = 2000,
) -> list[dict]:
    system = SYSTEM_TEMPLATE.format(sentinel=SENTINEL, context=format_context(chunks))
    return [
        {"role": "system", "content": system},
        *_trim_history(history, max_history, history_chars),
        {"role": "user", "content": question},
    ]
